src/Entity/Kamer.php
<?php

namespace App\Entity;

use App\Repository\KamerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KamerRepository::class)
 */
class Kamer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Soort::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $soort;

    /**
     * @ORM\Column(type="integer")
     */
    private $room_nr;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $bed;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSoort(): ?soort
    {
        return $this->soort;
    }

    public function setSoort(?soort $soort): self
    {
        $this->soort = $soort;

        return $this;
    }

    public function getRoomNr(): ?int
    {
        return $this->room_nr;
    }

    public function setRoomNr(int $room_nr): self
    {
        $this->room_nr = $room_nr;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBed(): ?int
    {
        return $this->bed;
    }

    public function setBed(int $bed): self
    {
        $this->bed = $bed;

        return $this;
    }
    public function __toString(): string
    {
        return (string) $this->id;
    }
}

src/Form/KamerType.php
<?php

namespace App\Form;

use App\Entity\Kamer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class KamerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('room_nr')
            ->add('price')
            ->add('description')
            ->add('name')
            ->add('bed')
            ->add('soort')
            ->add('imagefile', FileType::class, [
                'mapped' => false,
                'label' => 'Upload room image'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Kamer::class,
        ]);
    }
}

src/Controller/KamerController.php
<?php

namespace App\Controller;

use App\Entity\Kamer;
use App\Entity\Image;
use App\Form\KamerType;
use App\Repository\KamerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/kamer")
 */
class KamerController extends AbstractController
{
    /**
     * @Route("/", name="kamer_index", methods={"GET"})
     */
    public function index(KamerRepository $kamerRepository): Response
    {
        return $this->render('kamer/index.html.twig', [
            'kamers' => $kamerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="kamer_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $kamer = new Kamer();
        $image = new Image();

        $form = $this->createForm(KamerType::class, $kamer);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['imagefile']->getData();
            $uploads_directory = $this->getParameter('uploads_directory');
            $filename = md5(uniqid()) . '.' . pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_EXTENSION);
            $uploadedFile->move(
                $uploads_directory,
                $filename
            );
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($kamer);
            $entityManager->flush();
            $image->setKamer($kamer);
            $image->setImagefile($filename);
            $entityManager->persist($image);
            $entityManager->flush();


            return $this->redirectToRoute('kamer_index');
        }

        return $this->render('kamer/new.html.twig', [
            'kamer' => $kamer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kamer_show", methods={"GET"})
     */
    public function show(Kamer $kamer): Response
    {
        return $this->render('kamer/show.html.twig', [
            'kamer' => $kamer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="kamer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Kamer $kamer): Response
    {
        $form = $this->createForm(KamerType::class, $kamer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('kamer_index');
        }

        return $this->render('kamer/edit.html.twig', [
            'kamer' => $kamer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="kamer_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Kamer $kamer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$kamer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($kamer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('kamer_index');
    }
}

templates/kamer/_delete_form.html.twig
<form method="post" action="{{ path('kamer_delete', {'id': kamer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ kamer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/kamer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/kamer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Kamer{% endblock %}

{% block body %}
    <h1>Edit Kamer</h1>

    {{ include('kamer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('kamer_index') }}">back to list</a>

    {{ include('kamer/_delete_form.html.twig') }}
{% endblock %}

templates/kamer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kamer index{% endblock %}

{% block body %}
    <h1>Kamer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Room_nr</th>
                <th>Price</th>
                <th>Description</th>
                <th>Name</th>
                <th>Bed</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for kamer in kamers %}
            <tr>
                <td>{{ kamer.id }}</td>
                <td>{{ kamer.roomNr }}</td>
                <td>{{ kamer.price }}</td>
                <td>{{ kamer.description }}</td>
                <td>{{ kamer.name }}</td>
                <td>{{ kamer.bed }}</td>
                <td>
                    <a href="{{ path('kamer_show', {'id': kamer.id}) }}">show</a>
                    <a href="{{ path('kamer_edit', {'id': kamer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('kamer_new') }}">Create new</a>
{% endblock %}

templates/kamer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Kamer{% endblock %}

{% block body %}
    <h1>Create new Kamer</h1>

    {{ include('kamer/_form.html.twig') }}

    <a href="{{ path('kamer_index') }}">back to list</a>
{% endblock %}

templates/kamer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kamer{% endblock %}

{% block body %}
    <h1>Kamer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ kamer.id }}</td>
            </tr>
            <tr>
                <th>Room_nr</th>
                <td>{{ kamer.roomNr }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ kamer.price }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ kamer.description }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ kamer.name }}</td>
            </tr>
            <tr>
                <th>Bed</th>
                <td>{{ kamer.bed }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('kamer_index') }}">back to list</a>

    <a href="{{ path('kamer_edit', {'id': kamer.id}) }}">edit</a>

    {{ include('kamer/_delete_form.html.twig') }}
{% endblock %}